version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - shopping-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/shopping_list_db
    restart: always
    networks:
      - shopping-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - shopping-network

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    networks:
      - shopping-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command:
      - start
      - --https-certificate-file=/etc/x509/https/cert.pem
      - --https-certificate-key-file=/etc/x509/https/key.pem
      - --https-port=8443
      - --hostname=keycloak.80.211.200.112.nip.io
      - --db-url-host=keycloak-db
      - --db-url-port=5432
      - --db-url-database=keycloak
      - --db-username=keycloak
      - --db-password=password
      - --optimized


    volumes:
      - /root/keycloak-ssl:/etc/x509/https:ro
    ports:
      - "8443:8443"
    depends_on:
      - keycloak-db
    networks:
      - shopping-network

volumes:
  mongo-data:
  keycloak-db:

networks:
  shopping-network:
    driver: bridge
