version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

#  backend:
#    build:
#      context: ./backend
#    container_name: backend
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mongodb
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/shopping_list_db
#    restart: always

#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend
#    ports:
#      - "3000:80"  # Exposes frontend on localhost:3000
#    depends_on:
#      - backend
#    restart: always

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db

volumes:
  mongo-data:
  keycloak-db:
